[pytest]
markers =
    offline: marks tests that should be run without network access
    network: marks tests that require network access
    not_network: marks tests that should be run without network access (legacy alias)