#!/usr/bin/env python3
"""Build the M7-00 data capability inventory from static repo-derived metadata.

This script performs no network calls and does not inspect live endpoints. It writes
Markdown, JSON, and CSV inventory artifacts under docs/data_capabilities/.
"""
from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "data_capabilities"

NORMALIZED_OBSERVATION_FIELDS = [
    "schema_version", "symbol", "display_symbol", "category_id", "instrument_type", "status", "source",
    "adapter_id", "market", "source_type", "price_like_value", "value", "price_semantics",
    "source_timestamp", "retrieved_at_utc", "freshness_assessment", "delay_status", "delay_seconds",
    "staleness_seconds", "reference_only", "contract", "contract_month", "contract_selector",
    "data_quality_flags", "source_risk_flags", "caveats",
]

TWSE_RAW_FIELDS = ["c", "ex", "n", "ch", "z", "y", "o", "h", "l", "v", "tv", "b", "g", "a", "f", "u", "w", "d", "t", "tlong", "%", "ot"]
TAIFEX_RAW_FIELDS = ["CLastPrice", "SettlementPrice", "CRefPrice", "CDate", "CTime", "Status", "SymbolID", "DispEName", "DispCName"]

source_families: list[dict[str, Any]] = [
    {
        "source_id": "TWSE_MIS", "display_name": "TWSE MIS browser JSON stock/index quotes", "authority_class": "official_browser_json_candidate", "timing_class": "live_or_intraday", "source_availability_status": "implemented_normalized_now",
        "runtime_exposure_status": ["exposed_in_fastapi", "exposed_in_mcp", "exposed_in_frontend", "exposed_in_conversation_context", "fetched_but_dropped"],
        "repo_evidence": {"files": ["scripts/m5k_common.py", "scripts/observation_contract.py", "config/m5l_live_source_adapter_matrix.json"], "tests": ["tests/test_m5k_live_observation.py", "tests/test_m5n_conversation_context.py"], "docs": ["docs/protocol/TWSE_MIS_FIELD_DICTIONARY.md", "docs/protocol/TWSE_MIS_PROTOCOL.md", "docs/m5l_live_sources_validation_matrix.md"]},
        "source_url_template_or_artifact_path": "https://mis.twse.com.tw/stock/api/getStockInfo.jsp?ex_ch={tse|otc}_{symbol}.tw&json=1&delay=0",
        "implementation_files": ["scripts/m5k_common.py", "scripts/observation_contract.py"], "tests_covering_source": ["tests/test_m5k_live_observation.py", "tests/test_m5q_source_health.py"],
        "current_normalized_fields": NORMALIZED_OBSERVATION_FIELDS + ["price_source_field"],
        "raw_or_source_fields_available": TWSE_RAW_FIELDS,
        "fields_currently_dropped": ["previous_close", "open", "high", "low", "cumulative_volume", "latest_trade_volume", "bid_ladder", "ask_ladder", "limit_up", "limit_down", "display_name", "exchange", "channel"],
        "deterministic_metrics_possible": ["change", "change_percent", "range", "range_percent", "position_in_day_range", "spread", "top5_bid_volume", "top5_ask_volume", "top5_displayed_bid_ask_ratio"],
        "current_ai_context_usage": "Only one price-like value plus timestamp/freshness/caveats is surfaced for successful rows.",
        "potential_ai_context_usage": "Richer quote snapshot facts, displayed depth snapshot, day range, and bounded watchlist aggregates without trading interpretation.",
        "semantic_risks": ["medium_unofficial_contract_fragility", "high_realtime_claim_risk", "high_trading_interpretation_risk"],
        "stability_notes": "Implemented but fragile browser JSON contract; no official realtime SLA is asserted.", "credential_or_access_requirements": "No credentials; may require browser-like headers/cookie behavior and low-frequency usage.",
        "recommended_near_term_action": "M7A expand normalized observation contract using already-known TWSE MIS fields; do not add a new source.", "candidate_milestone": "M7A_rich_mis_observation_contract",
    },
    {
        "source_id": "TAIFEX_MIS", "display_name": "TAIFEX MIS TX futures QuoteList", "authority_class": "official_browser_json", "timing_class": "live_or_intraday", "source_availability_status": "implemented_normalized_now",
        "runtime_exposure_status": ["exposed_in_fastapi", "exposed_in_mcp", "exposed_in_frontend", "exposed_in_conversation_context", "fetched_but_dropped"],
        "repo_evidence": {"files": ["scripts/m5k_common.py", "scripts/observation_contract.py", "config/m5l_live_source_adapter_matrix.json"], "tests": ["tests/test_m5l_taifex_live_source.py", "tests/test_m5q_source_health.py"], "docs": ["docs/m5l_taifex_live_source_validation.md", "docs/m5k_taifex_tx_futures_preflight.md"]},
        "source_url_template_or_artifact_path": "POST https://mis.taifex.com.tw/futures/api/getQuoteList body CID=TXF",
        "implementation_files": ["scripts/m5k_common.py", "scripts/observation_contract.py"], "tests_covering_source": ["tests/test_m5l_taifex_live_source.py", "tests/test_m5k_live_observation.py"],
        "current_normalized_fields": NORMALIZED_OBSERVATION_FIELDS + ["source_status", "normalization"], "raw_or_source_fields_available": TAIFEX_RAW_FIELDS,
        "fields_currently_dropped": ["other_quote_list_contracts", "raw_quote_count", "open/high/low/reference/volume/bid/ask fields if present are not evident in current parser"],
        "deterministic_metrics_possible": ["change if CRefPrice and CLastPrice retained", "cross_instrument_change_diff when normalized"],
        "current_ai_context_usage": "Front-month TX value with contract metadata, timestamp, status, and caveats.", "potential_ai_context_usage": "TX context adjacent to TAIEX/watchlist if richer fields are validated.",
        "semantic_risks": ["high_realtime_claim_risk", "high_trading_interpretation_risk"], "stability_notes": "Official browser endpoint but not a licensed feed contract; current parser only proves selected fields.",
        "credential_or_access_requirements": "No credentials observed for bounded probe; licensed data may be needed for SLA-backed use.", "recommended_near_term_action": "M7A inspect fixture/evidence before adding richer fields; mark missing OHLC/depth as unknown until proven.", "candidate_milestone": "M7A_rich_mis_observation_contract",
    },
    {
        "source_id": "TWSE_OpenAPI", "display_name": "TWSE official OpenAPI EOD daily quote", "authority_class": "official_openapi", "timing_class": "end_of_day", "source_availability_status": "implemented_probe_or_contract_now", "runtime_exposure_status": ["docs_only", "contract_known_but_not_implemented", "normalized_but_not_exposed"],
        "repo_evidence": {"files": ["docs/contracts/twse_openapi_normalized_eod_quote_v1.md"], "tests": ["tests/test_source_contracts.py"], "docs": ["docs/protocol/TWSE_OPENAPI_FIELD_DICTIONARY.md", "docs/protocol/OFFICIAL_OPENAPI_SOURCE_SEMANTICS.md"]},
        "source_url_template_or_artifact_path": "https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL", "implementation_files": ["scripts/run_m3g04_controlled_live_probe.py"], "tests_covering_source": ["tests/test_source_contracts.py"],
        "current_normalized_fields": ["trade_date", "symbol", "name", "trade_volume", "trade_value", "open", "high", "low", "close", "change", "transaction_count"], "raw_or_source_fields_available": ["Date", "Code", "Name", "TradeVolume", "TradeValue", "OpeningPrice", "HighestPrice", "LowestPrice", "ClosingPrice", "Change", "Transaction"], "fields_currently_dropped": [],
        "deterministic_metrics_possible": ["range", "range_percent", "change_from_open_percent"], "current_ai_context_usage": "Canonical/EOD reference context, not current observation.", "potential_ai_context_usage": "Official EOD baseline for daily context and stale/reference comparisons.", "semantic_risks": ["medium_delayed_or_reference_only"], "stability_notes": "Official EOD endpoint; not intraday.", "credential_or_access_requirements": "No credentials.", "recommended_near_term_action": "M7C expand official EOD context after live snapshot expansion.", "candidate_milestone": "M7C_official_eod_context_expansion",
    },
    {
        "source_id": "TPEx_OpenAPI", "display_name": "TPEx official OpenAPI EOD daily close quotes", "authority_class": "official_openapi", "timing_class": "end_of_day", "source_availability_status": "implemented_probe_or_contract_now", "runtime_exposure_status": ["docs_only", "contract_known_but_not_implemented", "normalized_but_not_exposed"],
        "repo_evidence": {"files": ["docs/contracts/tpex_openapi_normalized_eod_quote_v1.md"], "tests": ["tests/test_source_contracts.py"], "docs": ["docs/protocol/TPEX_OPENAPI_FIELD_DICTIONARY.md", "docs/protocol/OFFICIAL_OPENAPI_SOURCE_SEMANTICS.md"]},
        "source_url_template_or_artifact_path": "https://www.tpex.org.tw/openapi/v1/tpex_mainboard_daily_close_quotes", "implementation_files": ["scripts/run_m3g04_controlled_live_probe.py"], "tests_covering_source": ["tests/test_source_contracts.py"],
        "current_normalized_fields": ["trade_date", "symbol", "name", "close", "change", "open", "high", "low", "trade_volume", "trade_value", "transaction_count"], "raw_or_source_fields_available": ["Date", "SecuritiesCompanyCode", "CompanyName", "Close", "Change", "Open", "High", "Low", "Average", "TradingShares", "TransactionAmount", "TransactionNumber", "LatestBidPrice", "LatesAskPrice", "Capitals", "NextReferencePrice", "NextLimitUp", "NextLimitDown"], "fields_currently_dropped": ["Average", "LatestBidPrice", "LatesAskPrice", "Capitals", "NextReferencePrice", "NextLimitUp", "NextLimitDown"],
        "deterministic_metrics_possible": ["range", "range_percent", "change_from_open_percent"], "current_ai_context_usage": "Official OTC EOD reference context.", "potential_ai_context_usage": "Official TPEx daily baseline and next-day reference context.", "semantic_risks": ["medium_delayed_or_reference_only"], "stability_notes": "Official EOD endpoint; one raw typo-like field name LatesAskPrice must be preserved exactly.", "credential_or_access_requirements": "No credentials.", "recommended_near_term_action": "M7C expand official EOD context and preserve unmapped official fields.", "candidate_milestone": "M7C_official_eod_context_expansion",
    },
    {
        "source_id": "Yahoo_Finance", "display_name": "Yahoo Finance chart endpoint", "authority_class": "unofficial_api", "timing_class": "historical", "source_availability_status": "implemented_probe_or_contract_now", "runtime_exposure_status": ["docs_only", "contract_known_but_not_implemented"], "repo_evidence": {"files": ["docs/contracts/yahoo_finance_normalized_chart_v1.md"], "tests": ["tests/test_generate_chatgpt_briefing.py"], "docs": ["docs/protocol/YAHOO_FINANCE_CHART_PROTOCOL.md", "docs/capability_matrix.md"]}, "source_url_template_or_artifact_path": "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}", "implementation_files": ["scripts/run_m3g04_controlled_live_probe.py"], "tests_covering_source": ["tests/test_generate_chatgpt_briefing.py"], "current_normalized_fields": ["symbol", "regular_market_price", "regular_market_time", "open", "high", "low", "close", "volume"], "raw_or_source_fields_available": ["meta", "timestamp", "indicators.quote.open/high/low/close/volume", "adjclose", "chart.error"], "fields_currently_dropped": ["full_intraday_series", "timezone_metadata", "currency", "exchangeName"], "deterministic_metrics_possible": ["range", "change_percent if previous close is present", "historical trend summaries"], "current_ai_context_usage": "Offline/not attempted or contract context; not a current normalized runtime source.", "potential_ai_context_usage": "Optional historical/chart context if coverage and delay are displayed.", "semantic_risks": ["medium_unofficial_contract_fragility", "medium_delayed_or_reference_only"], "stability_notes": "Unofficial endpoint with rate limits and coverage gaps.", "credential_or_access_requirements": "No credentials, but rate-limited.", "recommended_near_term_action": "M7D optional historical context only after explicit coverage validation.", "candidate_milestone": "M7D_optional_third_party_historical_context"},
    {"source_id": "FinMind", "display_name": "FinMind data API", "authority_class": "commercial_api", "timing_class": "historical", "source_availability_status": "validated_historical_workbench", "runtime_exposure_status": ["docs_only", "contract_known_but_not_implemented"], "repo_evidence": {"files": ["docs/capability_matrix.md"], "tests": [], "docs": ["docs/protocol/OFFICIAL_OPENAPI_SOURCE_SEMANTICS.md"]}, "source_url_template_or_artifact_path": "https://api.finmindtrade.com/api/v4/data", "implementation_files": ["scripts/run_m3g04_controlled_live_probe.py"], "tests_covering_source": [], "current_normalized_fields": ["historical/eod sample fields in prior capability matrix only"], "raw_or_source_fields_available": ["dataset-dependent"], "fields_currently_dropped": ["not integrated into runtime observation"], "deterministic_metrics_possible": ["historical returns/ranges if dataset validated"], "current_ai_context_usage": "Listed as historical/EOD candidate; not exposed in runtime context.", "potential_ai_context_usage": "Optional historical context package.", "semantic_risks": ["medium_delayed_or_reference_only", "high_credential_or_compliance_risk"], "stability_notes": "Commercial/API terms and tier limits apply.", "credential_or_access_requirements": "Token may be needed depending on dataset/tier.", "recommended_near_term_action": "M7D only; no credential assumptions.", "candidate_milestone": "M7D_optional_third_party_historical_context"},
    {"source_id": "Fugle_MarketData", "display_name": "Fugle MarketData API", "authority_class": "commercial_api", "timing_class": "credential_dependent", "source_availability_status": "credential_gated_not_usable_now", "runtime_exposure_status": ["docs_only"], "repo_evidence": {"files": ["config/m5l_live_source_adapter_matrix.json", "docs/capability_matrix.md"], "tests": [], "docs": ["docs/protocol/OFFICIAL_OPENAPI_SOURCE_SEMANTICS.md"]}, "source_url_template_or_artifact_path": "https://developer.fugle.tw/", "implementation_files": [], "tests_covering_source": [], "current_normalized_fields": [], "raw_or_source_fields_available": ["unknown_needs_credentials"], "fields_currently_dropped": ["all provider fields; no integration"], "deterministic_metrics_possible": ["unknown until provider contract validated"], "current_ai_context_usage": "Credential-gated future candidate only.", "potential_ai_context_usage": "Licensed read-only live provider if terms and credentials allow.", "semantic_risks": ["high_credential_or_compliance_risk", "high_realtime_claim_risk"], "stability_notes": "Requires credentials and compliance review.", "credential_or_access_requirements": "Personal API key/subscription required; do not commit credentials.", "recommended_near_term_action": "M7E provider research only.", "candidate_milestone": "M7E_credential_gated_provider_research"},
    {"source_id": "Fubon_Neo_API", "display_name": "Fubon Neo API", "authority_class": "broker_api", "timing_class": "credential_dependent", "source_availability_status": "credential_gated_not_usable_now", "runtime_exposure_status": ["docs_only"], "repo_evidence": {"files": ["config/m5l_live_source_adapter_matrix.json", "docs/capability_matrix.md"], "tests": [], "docs": ["docs/protocol/OFFICIAL_OPENAPI_SOURCE_SEMANTICS.md"]}, "source_url_template_or_artifact_path": "https://developer.fubon.com/", "implementation_files": [], "tests_covering_source": [], "current_normalized_fields": [], "raw_or_source_fields_available": ["unknown_needs_broker_credentials"], "fields_currently_dropped": ["all provider fields; no integration"], "deterministic_metrics_possible": ["unknown until non-trading read-only contract validated"], "current_ai_context_usage": "Credential-gated future candidate only.", "potential_ai_context_usage": "Possible read-only broker data after strict separation from order/execution features.", "semantic_risks": ["high_credential_or_compliance_risk", "high_trading_interpretation_risk"], "stability_notes": "Broker/account/certificate proximity raises compliance and safety risk.", "credential_or_access_requirements": "Brokerage account/certificate likely required; no credentials in repo.", "recommended_near_term_action": "M7E research only; no implementation until governance decision.", "candidate_milestone": "M7E_credential_gated_provider_research"},
]

# Add local/runtime source families required by task.
for sid, name, auth, timing, status, exposure, path, files, milestone in [
    ("Local_M5F_canonical_context", "Local M5F canonical context", "local_canonical_artifact", "local_static_context", "implemented_normalized_now", ["exposed_in_fastapi", "exposed_in_mcp", "exposed_in_frontend", "exposed_in_conversation_context"], "research/staging/m5f/m5f_canonical_market_context_01/canonical_market_context.json", ["server/main.py", "server/mcp_server.py", "scripts/validate_m5f_canonical_market_context_package.py"], "M7C_official_eod_context_expansion"),
    ("Local_M5K_latest_observation", "Local M5K latest observation", "local_generated_artifact", "live_or_intraday", "implemented_normalized_now", ["exposed_in_fastapi", "exposed_in_mcp", "exposed_in_frontend", "exposed_in_conversation_context"], "research/live_observation_runs/m5k/latest_observation.json", ["scripts/m5k_common.py", "server/main.py", "server/mcp_server.py"], "M7A_rich_mis_observation_contract"),
    ("Local_M5K_observation_history", "Local M5K observation history", "local_generated_artifact", "historical", "implemented_probe_or_contract_now", ["exposed_in_fastapi", "normalized_but_not_exposed"], "research/live_observation_runs/m5k/*.json", ["server/main.py"], "M7B_market_context_package_and_ai_markdown"),
    ("M5N_watchlist_conversation_handoff", "M5N watchlist / conversation handoff", "local_generated_artifact", "local_static_context", "implemented_normalized_now", ["exposed_in_fastapi", "exposed_in_mcp", "exposed_in_frontend", "exposed_in_conversation_context"], "config/m5k_default_watchlist.json", ["scripts/m5k_common.py", "scripts/build_m5n_conversation_context.py", "server/main.py", "server/mcp_server.py"], "M7B_market_context_package_and_ai_markdown"),
    ("M5Q_source_health_report", "M5Q source-health report", "local_generated_artifact", "source_health_probe", "implemented_probe_or_contract_now", ["exposed_in_fastapi", "exposed_in_mcp", "exposed_in_frontend", "exposed_in_conversation_context"], "research/live_observation_runs/source_health/latest_source_health_report.json", ["scripts/m5q_source_health.py", "scripts/run_m5q_source_health_probe.py", "server/main.py", "server/mcp_server.py"], "M7B_market_context_package_and_ai_markdown"),
    ("FastAPI_context_endpoints", "FastAPI readonly context endpoints", "local_generated_artifact", "local_static_context", "implemented_normalized_now", ["exposed_in_fastapi", "exposed_in_frontend"], "/api/context/*", ["server/main.py"], "M7B_market_context_package_and_ai_markdown"),
    ("FastAPI_live_observation_endpoints", "FastAPI live observation read/plan endpoints", "local_generated_artifact", "live_or_intraday", "implemented_normalized_now", ["exposed_in_fastapi", "exposed_in_frontend"], "/api/m5k/live-observation/latest", ["server/main.py"], "M7A_rich_mis_observation_contract"),
    ("FastAPI_conversation_context_endpoint", "FastAPI conversation context endpoint", "local_generated_artifact", "local_static_context", "implemented_normalized_now", ["exposed_in_fastapi", "exposed_in_frontend", "exposed_in_conversation_context"], "/api/conversation/context", ["server/main.py", "scripts/m5k_common.py"], "M7B_market_context_package_and_ai_markdown"),
    ("MCP_server_exposed_resources_tools", "MCP server exposed resources/tools", "local_generated_artifact", "local_static_context", "implemented_normalized_now", ["exposed_in_mcp", "exposed_in_conversation_context"], "server/mcp_server.py tools", ["server/mcp_server.py"], "M7B_market_context_package_and_ai_markdown"),
]:
    source_families.append({"source_id": sid, "display_name": name, "authority_class": auth, "timing_class": timing, "source_availability_status": status, "runtime_exposure_status": exposure, "repo_evidence": {"files": files, "tests": ["tests/"], "docs": ["README.md", "docs/operator/LOCAL_WORKBENCH.md"]}, "source_url_template_or_artifact_path": path, "implementation_files": files, "tests_covering_source": ["tests/"], "current_normalized_fields": NORMALIZED_OBSERVATION_FIELDS if "M5K" in sid or "live" in sid else ["governance", "summary", "content", "caveats"], "raw_or_source_fields_available": ["local artifact fields"], "fields_currently_dropped": ["raw endpoint payloads are intentionally excluded"], "deterministic_metrics_possible": ["watchlist counts", "freshness summaries", "source-health counts"], "current_ai_context_usage": "Provides local context to API/frontend/MCP/Conversation Package.", "potential_ai_context_usage": "Richer bounded summaries once source rows expose more facts.", "semantic_risks": ["low_reference_context" if timing == "local_static_context" else "medium_delayed_or_reference_only"], "stability_notes": "Local repo artifact or endpoint; no external network when reading.", "credential_or_access_requirements": "None.", "recommended_near_term_action": "Compose richer facts without changing runtime behavior in this PR.", "candidate_milestone": milestone})

metrics = [
    ("change", ["last_price", "previous_close"], ["TWSE_MIS", "TWSE_OpenAPI", "TPEx_OpenAPI"], "not_currently_available_for_live", "last minus previous close; descriptive only", "price difference", "signal/recommendation"),
    ("change_percent", ["last_price", "previous_close"], ["TWSE_MIS"], "not_currently_available_for_live", "change / previous close", "percentage move versus reference", "momentum call"),
    ("range", ["high", "low"], ["TWSE_MIS", "TWSE_OpenAPI", "TPEx_OpenAPI", "Yahoo_Finance"], "available_eod_not_live_exposed", "high minus low", "observed range", "support/resistance as fact"),
    ("range_percent", ["high", "low", "previous_close"], ["TWSE_MIS"], "not_currently_available_for_live", "range / previous close", "range relative to reference", "volatility prediction"),
    ("position_in_day_range", ["last_price", "high", "low"], ["TWSE_MIS"], "not_currently_available_for_live", "(last-low)/(high-low)", "location within observed day range", "entry/exit"),
    ("distance_from_high_percent", ["last_price", "high"], ["TWSE_MIS"], "not_currently_available_for_live", "(last-high)/high", "distance from observed high", "resistance"),
    ("distance_from_low_percent", ["last_price", "low"], ["TWSE_MIS"], "not_currently_available_for_live", "(last-low)/low", "distance from observed low", "support"),
    ("change_from_open_percent", ["last_price", "open"], ["TWSE_MIS"], "not_currently_available_for_live", "(last-open)/open", "change from open", "trade setup"),
    ("spread", ["best_ask", "best_bid"], ["TWSE_MIS"], "not_currently_available_for_live", "best ask minus best bid", "displayed spread snapshot", "liquidity guarantee"),
    ("spread_percent", ["best_ask", "best_bid", "last_price"], ["TWSE_MIS"], "not_currently_available_for_live", "spread / last", "displayed spread percent", "execution cost guarantee"),
    ("top5_bid_volume", ["bid_volumes"], ["TWSE_MIS"], "not_currently_available_for_live", "sum displayed bid volumes", "observed displayed bid depth", "institutional flow"),
    ("top5_ask_volume", ["ask_volumes"], ["TWSE_MIS"], "not_currently_available_for_live", "sum displayed ask volumes", "observed displayed ask depth", "institutional flow"),
    ("top5_displayed_bid_ask_ratio", ["bid_volumes", "ask_volumes"], ["TWSE_MIS"], "not_currently_available_for_live", "top bid volume / top ask volume", "displayed depth balance", "chip flow"),
    ("watchlist_advancers_count", ["change"], ["M5N_watchlist_conversation_handoff"], "candidate_after_M7A", "count change > 0", "bounded watchlist advancers", "ranking"),
    ("watchlist_decliners_count", ["change"], ["M5N_watchlist_conversation_handoff"], "candidate_after_M7A", "count change < 0", "bounded watchlist decliners", "ranking"),
    ("watchlist_unchanged_count", ["change"], ["M5N_watchlist_conversation_handoff"], "candidate_after_M7A", "count change == 0", "bounded watchlist unchanged", "ranking"),
    ("watchlist_unavailable_count", ["status"], ["M5N_watchlist_conversation_handoff"], "currently_possible", "count unavailable rows", "unavailable observations", "quality hidden"),
    ("cross_instrument_change_diff", ["change_percent"], ["TWSE_MIS", "TAIFEX_MIS"], "candidate_after_M7A", "difference between two observed changes", "bounded cross-instrument difference", "relative value recommendation"),
]

deterministic_metrics = [{"metric_id": m[0], "required_fields": m[1], "source_family_compatibility": m[2], "determinism": "deterministic_arithmetic", "current_availability": m[3], "semantic_risk": "high_trading_interpretation_risk" if m[0].startswith(("top5", "spread")) else "medium_delayed_or_reference_only", "ai_phrasing_allowed": m[5], "ai_phrasing_forbidden": m[6], "formula_or_description": m[4]} for m in metrics]

field_inventory = []
for raw, proposed, metric, caveat in [
    ("z", "last_price", "change/change_percent/range_position", "not official realtime; may be '-'"), ("y", "previous_close", "change/change_percent", "reference fallback is not current price"), ("o", "open", "change_from_open_percent", "may be placeholder"), ("h", "high", "range/position", "observed day high only"), ("l", "low", "range/position", "observed day low only"), ("v", "cumulative_volume", "volume summaries", "unit semantics need validation"), ("tv", "latest_trade_volume", "last-trade context", "may be placeholder"), ("b", "bid_prices", "spread/top5_depth", "displayed depth snapshot only"), ("g", "bid_volumes", "top5_bid_volume", "displayed depth snapshot only"), ("a", "ask_prices", "spread/top5_depth", "displayed depth snapshot only"), ("f", "ask_volumes", "top5_ask_volume", "displayed depth snapshot only"), ("t", "source_time", "freshness", "source-local time"), ("d", "source_date", "freshness", "source-local date"), ("tlong", "source_timestamp", "freshness", "preferred timestamp if valid"), ("ch", "channel", "route audit", "frontend channel"), ("ex", "exchange", "identity", "channel semantics"), ("n", "display_name", "labeling", "optional"), ("status/quote_state", "quote_state", "quality", "only if observed in source rows"),
]:
    normalized = raw in {"z", "y", "t", "d", "tlong"}
    field_inventory.append({"source_id": "TWSE_MIS", "raw_field_name": raw, "normalized_today": "yes" if normalized else "no", "exposed_today": "yes" if normalized and raw in {"z", "y", "t", "d", "tlong"} else "no", "proposed_normalized_field_name": proposed, "deterministic_metric_enabled": metric, "semantic_caveat": caveat})
for raw in TAIFEX_RAW_FIELDS:
    field_inventory.append({"source_id": "TAIFEX_MIS", "raw_field_name": raw, "normalized_today": "yes", "exposed_today": "yes", "proposed_normalized_field_name": raw.lower(), "deterministic_metric_enabled": "limited_current_value_or_freshness", "semantic_caveat": "Current parser evidence does not prove OHLC/volume/depth fields beyond listed names."})

roadmap = [
    {"milestone": "M7A_rich_mis_observation_contract", "scope": "Rich TWSE MIS / TAIFEX observation contract expansion; no new source; expose richer quote snapshot facts."},
    {"milestone": "M7B_market_context_package_and_ai_markdown", "scope": "Market Context Package plus richer AI Markdown/MCP context and bounded cross-instrument summaries."},
    {"milestone": "M7C_official_eod_context_expansion", "scope": "Official TWSE/TPEx EOD context expansion and canonical/recent daily baseline."},
    {"milestone": "M7D_optional_third_party_historical_context", "scope": "Optional Yahoo/FinMind historical context with coverage and delay caveats."},
    {"milestone": "M7E_credential_gated_provider_research", "scope": "Fugle/Fubon credential-gated provider research only; no implementation until compliance decisions exist."},
]

def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    keys: list[str] = []
    for row in rows:
        for k in row:
            if k not in keys:
                keys.append(k)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for row in rows:
            w.writerow({k: json.dumps(v, ensure_ascii=False) if isinstance(v, (list, dict)) else v for k, v in row.items()})

def md_table(rows: list[dict[str, Any]], keys: list[str]) -> str:
    out = ["| " + " | ".join(keys) + " |", "|" + "|".join(["---"] * len(keys)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(r.get(k, "")).replace("|", "\\|") for k in keys) + " |")
    return "\n".join(out)

def build_markdown(data: dict[str, Any]) -> str:
    lines = ["# Validated Endpoint Data Capability Inventory", "", "## Executive summary", "", "The current local product works, but the context surfaced to humans and AI is thin: successful live rows mostly expose one price-like value plus timestamp, freshness, and caveats. Repository evidence shows several source families and field contracts are available or partially implemented, especially TWSE MIS raw fields that are currently dropped by normalization. The main gap is therefore normalization, runtime exposure, and conversation-context composition, not only source discovery. Next implementation should be evidence-driven and preserve non-trading semantics.", "", "## Current architecture map", "", "- **Local canonical context:** M5F reads reviewed local artifacts through FastAPI, frontend, and MCP.", "- **Live bounded observation:** M5K can explicitly execute bounded TWSE MIS and TAIFEX observations; this PR did not run it.", "- **Conversation context:** M5N combines watchlist, canonical, latest observation, and source-health summaries without raw endpoint payloads.", "- **Source health:** M5Q records manual bounded health probe summaries; latest report is read-only unless operator executes the probe.", "- **Frontend:** readonly preview consumes local API endpoints and displays caveats.", "- **MCP:** exposes readonly/local tools plus explicit bounded execution tools guarded by confirmation.", "", "## Source family inventory", ""]
    for s in data["source_families"]:
        lines += [f"### {s['source_id']}", "", f"- **What it is:** {s['display_name']}", f"- **Repo evidence:** files={', '.join(s['repo_evidence']['files'])}; docs={', '.join(s['repo_evidence']['docs'])}", f"- **Current implementation status:** {s['source_availability_status']}; runtime={', '.join(s['runtime_exposure_status'])}", f"- **Available fields:** {', '.join(s['raw_or_source_fields_available'])}", f"- **Normalized/exposed fields:** {', '.join(s['current_normalized_fields'][:20])}{'...' if len(s['current_normalized_fields']) > 20 else ''}", f"- **Dropped fields:** {', '.join(s['fields_currently_dropped'])}", f"- **AI context value:** {s['potential_ai_context_usage']}", f"- **Semantic risks:** {', '.join(s['semantic_risks'])}", f"- **Recommended milestone:** {s['candidate_milestone']}", ""]
    lines += ["## Field-level gap analysis", "", "TWSE MIS is the clearest normalization gap. The raw item contract documents `z`, `y`, `o`, `h`, `l`, `v`, `tv`, bid/ask ladders, date/time, channel, exchange, and display name fields, but current live normalization mainly exposes price-like value, status, timestamp/freshness, flags, and caveats. TAIFEX normalization currently proves last/settlement/reference fallback, contract metadata, source status, and source time; repo contracts inspected here do not prove TAIFEX OHLC/volume/depth fields, so those remain unknown_needs_review rather than fabricated.", "", md_table(data["field_inventory"], ["source_id", "raw_field_name", "normalized_today", "exposed_today", "proposed_normalized_field_name", "deterministic_metric_enabled", "semantic_caveat"]), "", "## Deterministic metrics possible now", "", md_table(data["deterministic_metrics"], ["metric_id", "required_fields", "source_family_compatibility", "current_availability", "ai_phrasing_allowed", "ai_phrasing_forbidden"]), "", "## AI context expansion strategy", "", "- **Facts:** expose source fields as bounded observations with source time, retrieval time, freshness, and caveats.", "- **Deterministic derived metrics:** compute arithmetic metrics only when all required fields exist and quality flags permit.", "- **Bounded cross-instrument summaries:** summarize watchlist counts and differences without ranking or preference language.", "- **AI interpretation layer:** only context discussion; no trading advice, no targets, and no execution wording.", "", "## Semantic safety rules", "", "Allowed examples: observed displayed bid depth; bounded watchlist observation; reference-only; delayed or stale; not official realtime SLA.", "", "Forbidden examples: buy; sell; hold; target price; ranking; guaranteed realtime; support/resistance as fact; institutional chip flow unless supported by future verified data.", "", "## Recommended M7 roadmap", ""]
    for r in data["m7_candidate_roadmap"]:
        lines.append(f"- **{r['milestone']}:** {r['scope']}")
    lines += ["", "## README summary proposal", "", "README now links this report and the machine-readable JSON, explains that multiple source families exist, and states that raw availability is not the same as normalized/exposed availability. It also reiterates context-only, non-trading usage.", ""]
    return "\n".join(lines)

def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    data = {"schema_version": "m7_00_data_capability_inventory.v1", "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"), "governance": {"network_calls": False, "live_observation": False, "product_behavior_changed": False, "trading_signal": False, "recommendation": False}, "source_families": source_families, "field_inventory": field_inventory, "deterministic_metrics": deterministic_metrics, "m7_candidate_roadmap": roadmap}
    (OUT / "validated_endpoint_data_capability_inventory.json").write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    write_csv(OUT / "validated_endpoint_data_capability_matrix.csv", source_families)
    write_csv(OUT / "validated_endpoint_field_inventory.csv", field_inventory)
    write_csv(OUT / "ai_context_expansion_planning_matrix.csv", deterministic_metrics)
    (OUT / "VALIDATED_ENDPOINT_DATA_CAPABILITY_INVENTORY.md").write_text(build_markdown(data), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(source_families)} source families")

if __name__ == "__main__":
    main()
