#!/usr/bin/env python3
import json
import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_PATH = ROOT / "docs/data_capabilities/unified_market_evidence_capability_catalog.v1.json"
PORTABLE_JSON_PATH = ROOT / "skills/tw-market-evidence-agent/assets/unified_capability_catalog_portable.json"
PORTABLE_GUIDE_PATH = ROOT / "skills/tw-market-evidence-agent/references/capability_quick_guide.md"

def get_file_sha256(path: Path) -> str:
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()

def get_commit_sha() -> str:
    try:
        return subprocess.check_output(["git", "log", "-1", "--format=%H"], cwd=str(ROOT), text=True).strip()
    except Exception:
        return "unknown"

def generate_portable_json_obj(catalog: dict, sha256: str, commit_sha: str) -> dict:
    return {
        "schema_version": "unified_market_evidence_capability_catalog.v1",
        "portable_metadata": {
            "canonical_source_path": "docs/data_capabilities/unified_market_evidence_capability_catalog.v1.json",
            "canonical_sha256": sha256,
            "generated_from_commit": commit_sha,
            "generator_version": "M8R-05A-F2-v2"
        },
        "supported_markets": catalog.get("supported_markets", {}),
        "data_need_capabilities": catalog.get("data_need_capabilities", []),
        "execution": catalog.get("execution", {}),
        "bounds": catalog.get("bounds", {}),
        "known_limitations": catalog.get("known_limitations", [])
    }

def generate_portable_markdown_text(portable_data: dict, sha256: str) -> str:
    md_lines = [
        "# M8 AI Capability Quick Guide (Generated Projection)",
        "",
        "<!-- DO NOT EDIT THIS FILE MANUALLY. Generated by scripts/generate_portable_catalog.py -->",
        "",
        f"- **Canonical Capability Catalog SHA-256**: `{sha256}`",
        f"- **Generated From Commit**: `{portable_data['portable_metadata']['generated_from_commit']}`",
        "",
        "Use this guide to verify the supported capabilities and limits when composing Unified Requests.",
        "",
        "## 1. Supported Data Needs",
        "",
        "| Capability ID | Description | Supported Markets | Execution Gate |",
        "|---|---|---|---|",
    ]

    for cap in portable_data["data_need_capabilities"]:
        cid = cap["capability_id"]
        desc = cap["description"]
        markets = ", ".join(cap["supported_markets"])
        gate = "Approval Required" if cap["requires_approval_for_execution"] else "Direct (No Approval)"
        md_lines.append(f"| `{cid}` | {desc} | {markets} | {gate} |")

    md_lines.extend([
        "",
        "## 2. Market Support Status",
        ""
    ])

    for market, val in portable_data["supported_markets"].items():
        md_lines.append(f"- **{market}**: `{val.get('support_level')}`")

    md_lines.extend([
        "",
        "## 3. System Execution & Bounds Constraints",
        "",
        f"- **Default Target Limit**: `{portable_data['bounds'].get('default_target_limit')}` securities",
        f"- **Hard Target Limit**: `{portable_data['bounds'].get('hard_target_limit')}` securities",
        f"- **Default Operation Limit**: `{portable_data['bounds'].get('default_operation_limit')}` operations",
        f"- **Hard Operation Limit**: `{portable_data['bounds'].get('hard_operation_limit')}` operations",
        f"- **Preview Supported**: `{portable_data['execution'].get('preview_supported')}`",
        f"- **One-Shot Execution**: `{portable_data['execution'].get('one_shot_execution')}`",
        ""
    ])

    return "\n".join(md_lines) + "\n"

def main():
    if not CANONICAL_PATH.exists():
        print(f"ERROR: Canonical catalog not found at {CANONICAL_PATH}")
        return

    sha256 = get_file_sha256(CANONICAL_PATH)
    commit_sha = get_commit_sha()
    
    with open(CANONICAL_PATH, "r", encoding="utf-8") as f:
        catalog = json.load(f)

    portable_data = generate_portable_json_obj(catalog, sha256, commit_sha)
    
    with open(PORTABLE_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(portable_data, f, indent=2, ensure_ascii=False)
    print(f"Generated portable catalog JSON at: {PORTABLE_JSON_PATH.relative_to(ROOT)}")

    md_text = generate_portable_markdown_text(portable_data, sha256)
    with open(PORTABLE_GUIDE_PATH, "w", encoding="utf-8") as f:
        f.write(md_text)
    print(f"Generated human-readable guide markdown at: {PORTABLE_GUIDE_PATH.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
