#!/usr/bin/env python3
import json
import hashlib
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANONICAL_PATH = ROOT / "docs/data_capabilities/unified_market_evidence_capability_catalog.v3.json"
PORTABLE_JSON_PATH = ROOT / "skills/tw-market-evidence-agent/assets/unified_capability_catalog_portable.json"
PORTABLE_GUIDE_PATH = ROOT / "skills/tw-market-evidence-agent/references/capability_quick_guide.md"
# The checked-in portable projections are a CRLF byte contract.  Make that
# representation explicit so Windows and Linux generator runs reproduce it.
PORTABLE_OUTPUT_NEWLINE = "\r\n"

def get_file_sha256(path: Path) -> str:
    """Hash UTF-8 text with newline representation normalized to LF.

    The canonical catalog is a text contract.  Its semantic bytes must be
    stable whether a checkout materializes its line endings as LF, CRLF, or
    CR, without normalizing any other content.
    """
    text = path.read_bytes().decode("utf-8")
    normalized_text = text.replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(normalized_text.encode("utf-8")).hexdigest()

def get_canonical_source_lineage(canonical_path: Path) -> dict:
    """Return Git lineage when the canonical input is tracked in this repo."""
    try:
        relative_path = canonical_path.resolve().relative_to(ROOT.resolve()).as_posix()
    except ValueError:
        return {}

    def git_stdout(*args: str) -> str:
        completed = subprocess.run(
            ["git", *args], cwd=ROOT, capture_output=True, text=True, check=False
        )
        return completed.stdout.strip() if completed.returncode == 0 else ""

    lineage = {}
    commit = git_stdout("log", "-1", "--format=%H", "--", relative_path)
    blob = git_stdout("rev-parse", f"HEAD:{relative_path}")
    if commit:
        lineage["generated_from_commit"] = commit
    if blob:
        lineage["canonical_git_blob_sha"] = blob
    return lineage


def generate_portable_json_obj(
    catalog: dict, sha256: str, source_lineage: dict | None = None
) -> dict:
    metadata = {
        "canonical_source_path": "docs/data_capabilities/unified_market_evidence_capability_catalog.v3.json",
        "canonical_sha256": sha256,
        "generator_version": "PHASE-H-ACT-V3-v1",
    }
    metadata.update(source_lineage or {})
    return {
        "schema_version": catalog["schema_version"],
        "portable_metadata": metadata,
        "contract_versions": catalog["contract_versions"],
        "supported_markets": catalog.get("supported_markets", {}),
        "data_need_capabilities": catalog.get("data_need_capabilities", []),
        "execution": catalog.get("execution", {}),
        "bounds": catalog.get("bounds", {}),
        "known_limitations": catalog.get("known_limitations", []),
    }

def generate_portable_markdown_text(portable_data: dict, sha256: str) -> str:
    md_lines = [
        "# Unified Market Evidence Capability Quick Guide (Generated Projection)",
        "",
        "<!-- DO NOT EDIT THIS FILE MANUALLY. Generated by scripts/generate_portable_catalog.py -->",
        "",
        f"- **Canonical Capability Catalog SHA-256**: `{sha256}`",
        "",
        "Use this guide to verify the supported capabilities and limits when composing Unified Requests.",
        "",
        "`Support Status` is authoritative for executability. An approval boundary does not make a `contract_supported` capability a standalone executable route.",
        "",
        "## 1. Supported Data Needs",
        "",
        "| Capability ID | Support Status | Supported Markets | Approval Boundary | Coverage | History | Known Runtime Limitation |",
        "|---|---|---|---|---|---|---|",
    ]

    for cap in portable_data["data_need_capabilities"]:
        cid = cap["capability_id"]
        markets = ", ".join(cap["supported_markets"])
        gate = "Approval Required" if cap["requires_approval_for_execution"] else "Direct (No Approval)"
        coverage = ", ".join(cap.get("coverage_modes", [])) or "catalog-defined"
        history = "Yes" if cap.get("historical_lookup_supported") else "No"
        status = cap["support_status"]
        limitations = "; ".join(cap.get("known_limitations", [])) or "catalog-defined"
        if status != "runtime_executable":
            limitations = f"Not currently runtime-executable; {limitations}"
        md_lines.append(
            f"| `{cid}` | `{status}` | {markets} | {gate} | {coverage} | {history} | {limitations} |"
        )

    md_lines.extend([
        "",
        "## 2. Market Support Status",
        ""
    ])

    for market, val in portable_data["supported_markets"].items():
        md_lines.append(f"- **{market}**: `{val.get('support_level')}`")

    md_lines.extend([
        "",
        "## 3. System Execution & Bounds Constraints",
        "",
        f"- **Default Target Limit**: `{portable_data['bounds'].get('default_target_limit')}` securities",
        f"- **Hard Target Limit**: `{portable_data['bounds'].get('hard_target_limit')}` securities",
        f"- **Default Operation Limit**: `{portable_data['bounds'].get('default_operation_limit')}` operations",
        f"- **Hard Operation Limit**: `{portable_data['bounds'].get('hard_operation_limit')}` operations",
        f"- **Preview Supported**: `{portable_data['execution'].get('preview_supported')}`",
        f"- **One-Shot Execution**: `{portable_data['execution'].get('one_shot_execution')}`",
        "",
        "## 4. Current Evidence Boundaries",
        "",
        "- Material disclosures cover the latest completed official daily batch for eligible TWSE/TPEX company common shares.",
        "- Monthly revenue covers the latest available official reporting period for eligible TWSE/TPEX company common shares; currency is TWD and unit is thousand.",
        "- Research acquisition uses official CSV first and governed official JSON OpenAPI fallback. Fallback use is explicit in evidence.",
        "- Phase H trading-status context is executable only through explicitly activated routes; current H1 coverage is partial and does not imply complete surveillance-status coverage.",
        "- Corporate-action context and recent-performance routes remain inactive/plan-only until their independent activation gates pass; derived discontinuity safety never fabricates complete coverage.",
        "- There is no arbitrary history, polling, scheduler, background refresh, financial summary, investment advice, or trading.",
        ""
    ])

    return "\n".join(md_lines) + "\n"

def generate_portable_catalog(
    *,
    canonical_path: Path,
    portable_json_path: Path,
    portable_guide_path: Path,
) -> str:
    """Generate portable projections at caller-selected bounded paths."""
    sha256 = get_file_sha256(canonical_path)
    with canonical_path.open("r", encoding="utf-8") as f:
        catalog = json.load(f)

    portable_data = generate_portable_json_obj(
        catalog, sha256, get_canonical_source_lineage(canonical_path)
    )

    portable_json_path.parent.mkdir(parents=True, exist_ok=True)
    portable_guide_path.parent.mkdir(parents=True, exist_ok=True)
    with portable_json_path.open(
        "w", encoding="utf-8", newline=PORTABLE_OUTPUT_NEWLINE
    ) as f:
        json.dump(portable_data, f, indent=2, ensure_ascii=False)

    md_text = generate_portable_markdown_text(portable_data, sha256)
    with portable_guide_path.open(
        "w", encoding="utf-8", newline=PORTABLE_OUTPUT_NEWLINE
    ) as f:
        f.write(md_text)
    return sha256


def main():
    if not CANONICAL_PATH.exists():
        print(f"ERROR: Canonical catalog not found at {CANONICAL_PATH}")
        return

    generate_portable_catalog(
        canonical_path=CANONICAL_PATH,
        portable_json_path=PORTABLE_JSON_PATH,
        portable_guide_path=PORTABLE_GUIDE_PATH,
    )
    print(f"Generated portable catalog JSON at: {PORTABLE_JSON_PATH.relative_to(ROOT)}")
    print(f"Generated human-readable guide markdown at: {PORTABLE_GUIDE_PATH.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
